export type BankLogoOption = {
  key: string;
  label: string;
  imageSrc: string;
};

export const bankLogoOptions: BankLogoOption[] = [
  { key: "logo:abc-brasil", label: "ABC Brasil", imageSrc: "/brands/banks/abc-brasil.svg" },
  { key: "logo:ailos", label: "Ailos", imageSrc: "/brands/banks/ailos.svg" },
  { key: "logo:banco-arbi", label: "Banco Arbi", imageSrc: "/brands/banks/banco-arbi.svg" },
  { key: "logo:banco-bmg", label: "Banco BMG", imageSrc: "/brands/banks/banco-bmg.svg" },
  { key: "logo:banco-bmp", label: "Banco BMP", imageSrc: "/brands/banks/banco-bmp.svg" },
  { key: "logo:banco-bs2-s-a", label: "Banco BS2 S.A", imageSrc: "/brands/banks/banco-bs2-s-a.svg" },
  { key: "logo:banco-btg-pacutal", label: "Banco BTG Pacutal", imageSrc: "/brands/banks/banco-btg-pacutal.svg" },
  { key: "logo:banco-c6-s-a", label: "Banco C6 S.A", imageSrc: "/brands/banks/banco-c6-s-a.svg" },
  { key: "logo:banco-da-amazonia-s-a", label: "Banco da Amazonia S.A", imageSrc: "/brands/banks/banco-da-amazonia-s-a.svg" },
  { key: "logo:banco-daycoval", label: "Banco Daycoval", imageSrc: "/brands/banks/banco-daycoval.svg" },
  { key: "logo:banco-do-brasil-s-a", label: "Banco do Brasil S.A", imageSrc: "/brands/banks/banco-do-brasil-s-a.svg" },
  { key: "logo:banco-do-estado-do-espirito-santo", label: "Banco do Estado do Espirito Santo", imageSrc: "/brands/banks/banco-do-estado-do-espirito-santo.svg" },
  { key: "logo:banco-do-estado-do-para", label: "Banco do Estado do Para", imageSrc: "/brands/banks/banco-do-estado-do-para.svg" },
  { key: "logo:banco-do-estado-do-sergipe", label: "Banco do Estado do Sergipe", imageSrc: "/brands/banks/banco-do-estado-do-sergipe.svg" },
  { key: "logo:banco-do-nordeste-do-brasil-s-a", label: "Banco do Nordeste do Brasil S.A", imageSrc: "/brands/banks/banco-do-nordeste-do-brasil-s-a.svg" },
  { key: "logo:banco-industrial-do-brasil-s-a", label: "Banco Industrial do Brasil S.A", imageSrc: "/brands/banks/banco-industrial-do-brasil-s-a.svg" },
  { key: "logo:banco-inter-s-a", label: "Banco Inter S.A", imageSrc: "/brands/banks/banco-inter-s-a.svg" },
  { key: "logo:banco-mercantil-do-brasil-s-a", label: "Banco Mercantil do Brasil S.A", imageSrc: "/brands/banks/banco-mercantil-do-brasil-s-a.svg" },
  { key: "logo:banco-original-s-a", label: "Banco Original S.A", imageSrc: "/brands/banks/banco-original-s-a.svg" },
  { key: "logo:banco-paulista", label: "Banco Paulista", imageSrc: "/brands/banks/banco-paulista.svg" },
  { key: "logo:banco-pine", label: "Banco Pine", imageSrc: "/brands/banks/banco-pine.svg" },
  { key: "logo:banco-rendimento", label: "Banco Rendimento", imageSrc: "/brands/banks/banco-rendimento.svg" },
  { key: "logo:banco-safra-s-a", label: "Banco Safra S.A", imageSrc: "/brands/banks/banco-safra-s-a.svg" },
  { key: "logo:banco-santander-brasil-s-a", label: "Banco Santander Brasil S.A", imageSrc: "/brands/banks/banco-santander-brasil-s-a.svg" },
  { key: "logo:banco-sofisa", label: "Banco Sofisa", imageSrc: "/brands/banks/banco-sofisa.svg" },
  { key: "logo:banco-topazio", label: "Banco Topazio", imageSrc: "/brands/banks/banco-topazio.svg" },
  { key: "logo:banco-triangulo-tribanco", label: "Banco Triangulo - Tribanco", imageSrc: "/brands/banks/banco-triangulo-tribanco.svg" },
  { key: "logo:banco-votorantim", label: "Banco Votorantim", imageSrc: "/brands/banks/banco-votorantim.svg" },
  { key: "logo:bank-of-america", label: "Bank of America", imageSrc: "/brands/banks/bank-of-america.svg" },
  { key: "logo:banrisul", label: "Banrisul", imageSrc: "/brands/banks/banrisul.svg" },
  { key: "logo:bk-bank", label: "BK Bank", imageSrc: "/brands/banks/bk-bank.svg" },
  { key: "logo:bnp-paripas", label: "BNP Paripas", imageSrc: "/brands/banks/bnp-paripas.svg" },
  { key: "logo:bradesco-s-a", label: "Bradesco S.A", imageSrc: "/brands/banks/bradesco-s-a.svg" },
  { key: "logo:brb-banco-de-brasilia", label: "BRB - Banco de Brasilia", imageSrc: "/brands/banks/brb-banco-de-brasilia.svg" },
  { key: "logo:caixa-economica-federal", label: "Caixa Economica Federal", imageSrc: "/brands/banks/caixa-economica-federal.svg" },
  { key: "logo:capitual", label: "Capitual", imageSrc: "/brands/banks/capitual.svg" },
  { key: "logo:conta-simples-solucoes-em-pagamentos", label: "Conta Simples Solucoes em Pagamentos", imageSrc: "/brands/banks/conta-simples-solucoes-em-pagamentos.svg" },
  { key: "logo:contbank", label: "Contbank", imageSrc: "/brands/banks/contbank.svg" },
  { key: "logo:cora-sociedade-credito-direto-s-a", label: "Cora Sociedade Credito Direto S.A", imageSrc: "/brands/banks/cora-sociedade-credito-direto-s-a.svg" },
  { key: "logo:credisis", label: "Credisis", imageSrc: "/brands/banks/credisis.svg" },
  { key: "logo:cresol", label: "Cresol", imageSrc: "/brands/banks/cresol.svg" },
  { key: "logo:duepay", label: "DuePay", imageSrc: "/brands/banks/duepay.svg" },
  { key: "logo:efi-gerencianet", label: "Efi - Gerencianet", imageSrc: "/brands/banks/efi-gerencianet.svg" },
  { key: "logo:grafeno", label: "Grafeno", imageSrc: "/brands/banks/grafeno.svg" },
  { key: "logo:infinitepay", label: "InfinitePay", imageSrc: "/brands/banks/infinitepay.svg" },
  { key: "logo:ip4y", label: "Ip4y", imageSrc: "/brands/banks/ip4y.svg" },
  { key: "logo:itau-unibanco-s-a", label: "Itau Unibanco S.A", imageSrc: "/brands/banks/itau-unibanco-s-a.svg" },
  { key: "logo:iugo", label: "Iugo", imageSrc: "/brands/banks/iugo.svg" },
  { key: "logo:lets-bank-s-a", label: "Lets Bank S.A", imageSrc: "/brands/banks/lets-bank-s-a.svg" },
  { key: "logo:linker", label: "Linker", imageSrc: "/brands/banks/linker.svg" },
  { key: "logo:magalupay", label: "MagaluPay", imageSrc: "/brands/banks/magalupay.svg" },
  { key: "logo:mercado-pago", label: "Mercado Pago", imageSrc: "/brands/banks/mercado-pago.svg" },
  { key: "logo:modobank", label: "ModoBank", imageSrc: "/brands/banks/modobank.svg" },
  { key: "logo:mufg", label: "MUFG", imageSrc: "/brands/banks/mufg.svg" },
  { key: "logo:multiplo-bank", label: "Multiplo Bank", imageSrc: "/brands/banks/multiplo-bank.svg" },
  { key: "logo:nu-pagamentos-s-a", label: "Nu Pagamentos S.A", imageSrc: "/brands/banks/nu-pagamentos-s-a.svg" },
  { key: "logo:omie-cash", label: "Omie.Cash", imageSrc: "/brands/banks/omie-cash.svg" },
  { key: "logo:omni", label: "Omni", imageSrc: "/brands/banks/omni.svg" },
  { key: "logo:pagseguro-internet-s-a", label: "PagSeguro Internet S.A", imageSrc: "/brands/banks/pagseguro-internet-s-a.svg" },
  { key: "logo:paycash", label: "PayCash", imageSrc: "/brands/banks/paycash.svg" },
  { key: "logo:picpay", label: "PicPay", imageSrc: "/brands/banks/picpay.svg" },
  { key: "logo:pinbank", label: "PinBank", imageSrc: "/brands/banks/pinbank.svg" },
  { key: "logo:quality-digital-bank", label: "Quality Digital Bank", imageSrc: "/brands/banks/quality-digital-bank.svg" },
  { key: "logo:recargapay", label: "RecargaPay", imageSrc: "/brands/banks/recargapay.svg" },
  { key: "logo:sicoob", label: "Sicoob", imageSrc: "/brands/banks/sicoob.svg" },
  { key: "logo:sicredi", label: "Sicredi", imageSrc: "/brands/banks/sicredi.svg" },
  { key: "logo:sisprime", label: "Sisprime", imageSrc: "/brands/banks/sisprime.svg" },
  { key: "logo:squid-solucoes-financeiras", label: "Squid Solucoes Financeiras", imageSrc: "/brands/banks/squid-solucoes-financeiras.svg" },
  { key: "logo:starbank", label: "StarBank", imageSrc: "/brands/banks/starbank.svg" },
  { key: "logo:stone-pagamentos-s-a", label: "Stone Pagamentos S.A", imageSrc: "/brands/banks/stone-pagamentos-s-a.svg" },
  { key: "logo:sulcredi", label: "Sulcredi", imageSrc: "/brands/banks/sulcredi.svg" },
  { key: "logo:transfera", label: "Transfera", imageSrc: "/brands/banks/transfera.svg" },
  { key: "logo:unicred", label: "Unicred", imageSrc: "/brands/banks/unicred.svg" },
  { key: "logo:uniprime", label: "Uniprime", imageSrc: "/brands/banks/uniprime.svg" },
  { key: "logo:xp-investimentos", label: "XP Investimentos", imageSrc: "/brands/banks/xp-investimentos.svg" },
] as const;
